#%RAML 0.8
title: Virtual Machines service
version: 1.0
baseUri: https://etics.res.eng.it/eticsbtem/api/virtualenvironment/
securitySchemes:
   - basic:
      type: Basic Authentication
      description: Basic authentication
/{virtualenvironmentId}/virtualmachine:
  uriParameters:
    virtualenvironmentId:
      description: 
      type: integer
      required: false
      displayName: virtualenvironmentId      
  post:
    description: creates a new Virtual Machine
    body:
      application/json:
        example: '{"id":"scaseVirtualMachine","cpuPower":"34","hdDimension":"20"}'
    responses:
        200:
          description: Virtual Environments created
          body:
            application/json:
              schema: "hyperlink_schema"
  get:
    description: Get the list of Virtual Machines
    responses:
        200:
          description: Virtual Environments created
          body:
            application/json:
              schema: "hyperlink_schema"
      
  /{virtualmachineId}:
    uriParameters:
      virtualmachineId:
        description: 
        type: integer
        required: false
        displayName: virtualmachineId
    get:
      description: Get the details of a Virtual Machine
      responses:
          200:
            description: Virtual Environments created
            body:
              application/json:
                schema: "hyperlink_schema"
    put:
      description: Modify Virtual Machine
      body:
        application/json:
          example: '{"cpuPower":"34","hdDimension":"20"}'
      responses:
          200:
            description: Virtual Environments created
            body:
              application/json:
                schema: "hyperlink_schema"
    delete:
      description: Modify Virtual Machine
      responses:
          200:
            description: Virtual Environments created
            body:
              application/json:
                schema: "hyperlink_schema"
